"""The reconciliation: what the shared cluster merge does with a satellite row.

`tree_dedup.preql` is planned and run here exactly as a city refresh would run
it -- the SF model's own SQL, generated by pytrilogy, with the four python
sources and the staged OSM parquet repointed at fixture parquets -- so what is
asserted is what a build would publish for these rows.  A reviewed detection
has to sit in a precise place in the merge:

* linked to an inventory tree, it is absorbed by that tree and leaves its id
  and label in the provenance columns;
* near an inventory tree that arrived later, it is absorbed the same way,
  the inventory position wins and the detection's species only fills a gap;
* alone, it publishes as its own tree and anchors any OSM node beside it;
* beside a person's submission, the submission owns the cluster.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

import pytest

RAW_DIR = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(RAW_DIR))

MODEL = RAW_DIR / "ussfo" / "sf_tree_info.preql"

# Five well-separated points; partners sit within 2 m of each, inside the 5 m
# the 10 m SF cell guarantees.
P1 = (37.7700, -122.4200)
P2 = (37.7750, -122.4250)
P3 = (37.7800, -122.4300)
P4 = (37.7850, -122.4350)
P5 = (37.7900, -122.4400)
NUDGE = 0.000012  # ~1.3 m of latitude


def near(point):
    return (point[0] + NUDGE, point[1])


ROW_COLUMNS = (
    "tree_id, city, data_source, species, tree_name, plant_date, "
    "diameter_at_breast_height, latitude, longitude, submission_photo_url, cultivar"
)

# (tree_id, data_source, species, dbh, point)
MUNICIPAL = [
    ("sf-1", "SF_OPENDATA", "Quercus agrifolia", 20.0, P1),
    ("sf-2", "SF_OPENDATA", "Unknown", None, P3),
]
COMMUNITY = [
    ("community-x", "COMMUNITY_USSFO", "Acer rubrum", None, P4),
    ("community-y", "COMMUNITY_USSFO", "Unknown", None, P5),
]
SATELLITE = [
    # Linked by the reviewer: exported at sf-1's own coordinates.
    ("sat-a", "SATELLITE_USSFO", "Quercus agrifolia", None, P1),
    # Alone: publishes as its own tree.
    ("sat-b", "SATELLITE_USSFO", "Platanus x hispanica", None, P2),
    # Beside an inventory row that has no species.
    ("sat-c", "SATELLITE_USSFO", "Ficus microcarpa", None, near(P3)),
    # Beside a person's submission.
    ("sat-d", "SATELLITE_USSFO", "Acer platanoides", None, near(P4)),
    # Beside a submission and an OSM node.
    ("sat-e", "SATELLITE_USSFO", "Pinus radiata", None, near(P5)),
]
OSM = [
    ("osm-1", "OSM_USSFO", None, None, near(P2)),
    ("osm-2", "OSM_USSFO", None, None, near(P5)),
]


def write_rows(conn, path: Path, rows, *, rename: dict[str, str] | None = None) -> None:
    conn.execute("DROP TABLE IF EXISTS src")
    conn.execute(
        """
        CREATE TABLE src (
            tree_id VARCHAR, city VARCHAR, data_source VARCHAR, species VARCHAR,
            tree_name VARCHAR, plant_date DATE, diameter_at_breast_height DOUBLE,
            latitude DOUBLE, longitude DOUBLE, submission_photo_url VARCHAR, cultivar VARCHAR
        )
        """
    )
    conn.executemany(
        "INSERT INTO src VALUES (?, 'USSFO', ?, ?, NULL, NULL, ?, ?, ?, NULL, NULL)",
        [(tree_id, source, species, dbh, *point) for tree_id, source, species, dbh, point in rows],
    )
    select = ", ".join(
        f"{col} AS {(rename or {}).get(col, col)}" for col in ROW_COLUMNS.split(", ")
    )
    conn.execute(f"COPY (SELECT {select} FROM src) TO '{path.as_posix()}' (FORMAT PARQUET)")


@pytest.fixture(scope="module")
def published(tmp_path_factory) -> dict[str, dict]:
    import duckdb
    from trilogy import Dialects, Environment
    from trilogy.dialect.config import DuckDBConfig

    tmp = tmp_path_factory.mktemp("reconciliation")
    conn = duckdb.connect()
    fixtures = {
        "sf_tree_info.py": tmp / "municipal.parquet",
        "community_tree_info.py": tmp / "community.parquet",
        "satellite_tree_info.py": tmp / "satellite.parquet",
        "ussfo_osm_staging.parquet": tmp / "osm.parquet",
    }
    # Every one of the four scripts emits canonical names, so none of these
    # needs a rename.  The SF script used to emit the portal's own spelling
    # (treeid, qspecies, plantdate, dbh) and this fixture renamed to match --
    # which is why this test is the one that fails when the ingest and the
    # model disagree about a column.  A dry run will not: it plans the model
    # without ever executing the python datasource.
    write_rows(conn, fixtures["sf_tree_info.py"], MUNICIPAL)
    write_rows(conn, fixtures["community_tree_info.py"], COMMUNITY)
    write_rows(conn, fixtures["satellite_tree_info.py"], SATELLITE)
    write_rows(conn, fixtures["ussfo_osm_staging.parquet"], OSM)

    env = Environment(working_path=MODEL.parent)
    env.parse(MODEL.read_text(encoding="utf-8"))
    executor = Dialects.DUCK_DB.default_executor(
        environment=env, conf=DuckDBConfig(enable_python_datasources=True)
    )
    # The same call `trilogy refresh` makes for a stale target: the planner
    # hides the target and derives it from its partitions, so the SQL is the
    # build's own.
    sql = executor.update_datasource(env.datasources["sf_tree_info"], dry_run=True)
    assert sql is not None
    # `CREATE OR REPLACE TABLE "<gcs address>" (...); INSERT INTO "<gcs address>" WITH ...`:
    # keep the query, drop the two statements that would write the object.
    sql = re.sub(r'^.*?INSERT INTO "[^"]*"\s*', "", sql, count=1, flags=re.S)
    assert sql.lstrip().upper().startswith("WITH"), sql[:200]

    # Every freshness probe answers one constant; the columns cover all four.
    probe = (
        "(SELECT TIMESTAMPTZ '2026-01-01 00:00:00+00' AS data_updated_through, "
        "TIMESTAMPTZ '2026-01-01 00:00:00+00' AS ussfo_community_data_updated_through, "
        "TIMESTAMPTZ '2026-01-01 00:00:00+00' AS ussfo_satellite_data_updated_through)"
    )

    def repoint(match: re.Match) -> str:
        script = Path(match.group(1)).name
        if script in fixtures:
            return f"read_parquet('{fixtures[script].as_posix()}')"
        assert script.endswith(("_update_time.py", "_probe.py")), script
        return probe

    sql = re.sub(r"uv_run\('([^']+)'(?:,\s*args := '(?:[^']|'')*')?\)", repoint, sql)
    sql = re.sub(
        r"read_parquet\('[^']*ussfo_osm_staging\.parquet[^']*'\)",
        f"read_parquet('{fixtures['ussfo_osm_staging.parquet'].as_posix()}')",
        sql,
    )
    assert "uv_run" not in sql and "storage.googleapis.com" not in sql, sql
    columns = [d[0] for d in conn.execute(sql).description]
    rows = [dict(zip(columns, row)) for row in conn.execute(sql).fetchall()]
    return {row["tree_id"]: row for row in rows}


def sources(row) -> list[str]:
    return row["merged_sources"].split(",")


def absorbed(row) -> list[str]:
    return (row["merged_tree_ids"] or "").split(",") if row["merged_tree_ids"] else []


def test_one_survivor_per_cluster(published):
    assert set(published) == {"sf-1", "sat-b", "sf-2", "community-x", "community-y"}


def test_a_linked_detection_is_absorbed_by_its_inventory_tree(published):
    row = published["sf-1"]
    assert absorbed(row) == ["sat-a"]
    assert sources(row) == ["SATELLITE_USSFO", "SF_OPENDATA"]
    # The inventory's own values win: measured diameter, trunk position.
    assert row["diameter_at_breast_height"] == 20.0
    assert (row["latitude"], row["longitude"]) == P1


def test_a_detection_fills_the_gaps_an_inventory_row_left(published):
    """The city published sf-2 with no species; the reviewed detection beside
    it supplies one, while the inventory position is kept."""
    row = published["sf-2"]
    assert absorbed(row) == ["sat-c"]
    assert row["species"] == "Ficus microcarpa"
    assert (row["latitude"], row["longitude"]) == P3


def test_a_lone_detection_publishes_and_anchors_osm(published):
    row = published["sat-b"]
    assert row["species"] == "Platanus x hispanica"
    assert absorbed(row) == ["osm-1"]
    assert sources(row) == ["OSM_USSFO", "SATELLITE_USSFO"]
    assert (row["latitude"], row["longitude"]) == P2


def test_a_submission_owns_its_cluster_over_a_detection(published):
    row = published["community-x"]
    assert absorbed(row) == ["sat-d"]
    # Community first: the person's identification beats the model's.
    assert row["species"] == "Acer rubrum"
    assert (row["latitude"], row["longitude"]) == P4


def test_a_detection_and_an_osm_node_both_join_a_submission(published):
    row = published["community-y"]
    assert absorbed(row) == ["osm-2", "sat-e"]
    # The submission had no identification; the most specific name wins.
    assert row["species"] == "Pinus radiata"
    assert sources(row) == ["COMMUNITY_USSFO", "OSM_USSFO", "SATELLITE_USSFO"]
