import { frame, onCurve, point, simpleLeaf, stem, tangent } from './botanical-geometry.mjs'

// Pine-inspired paired needles and a low, small-leaved understory spray.
// Sparse fascicles distinguish this study from the flat temperate fir fans.
export const borealScene = {
  twig: { base: [399, 513], bend: [319, 360], tip: [271, 198] },
  leader: { count: 9, length: 83 },
  branches: [
    { at: .38, bend: [267, 384], tip: [195, 312], count: 8, length: 72 },
    { at: .65, bend: [366, 319], tip: [385, 255], count: 8, length: 72 },
  ],
  shrub: { base: [356, 513], bend: [249, 469], tip: [188, 403] },
  leaves: [
    { at: .25, side: 1, length: 39, width: 16 },
    { at: .40, side: -1, length: 44, width: 18 },
    { at: .61, side: 1, length: 40, width: 17 },
    { at: .79, side: -1, length: 37, width: 16 },
  ],
}

function pineNeedles(curve, { count, length }) {
  const paths = []
  for (let index = 0; index < count; index++) {
    const progress = index / (count - 1)
    const t = .76 + .24 * progress
    const origin = onCurve(curve, t)
    const position = frame(origin, tangent(curve, t))
    // Alternate sides up the shoot, so each pair opens into its own space.
    const side = index % 2 ? 1 : -1
    const angle = side * (1.12 - .91 * progress)
    const size = length * (.79 + .21 * Math.sin(Math.PI * progress))
    for (const spread of [-.025, .025]) {
      const a = angle + spread
      const tip = position(Math.sin(a) * size, Math.cos(a) * size)
      const bend = position(Math.sin(a) * size * .7, Math.cos(a) * size * .42)
      paths.push(`M${point(origin)} Q${point(bend)} ${point(tip)}`)
    }
  }
  return paths.join(' ')
}

export function generateBorealSvg() {
  const { twig, leader, shrub } = borealScene
  const branches = borealScene.branches.map(branch => ({ ...branch, base: onCurve(twig, branch.at) }))
  const petioles = borealScene.leaves.map(leaf => {
    const base = onCurve(shrub, leaf.at)
    const local = frame(base, tangent(shrub, leaf.at))
    return { ...leaf, base, bend: local(leaf.side * 9, 4), tip: local(leaf.side * 17, 10) }
  })
  const leaves = [...petioles, { ...shrub, length: 42, width: 17 }].map(leaf => simpleLeaf(leaf, leaf.length, leaf.width))
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 460 510" fill="none" stroke="currentColor" stroke-width="1.15" stroke-linecap="round" stroke-linejoin="round">
  <!-- Generated by generators/boreal.mjs; edit the scene, then pnpm artwork:generate. -->
  <g class="contours" opacity=".35" stroke-width=".7"><path d="M18 478Q65 465 105 475T186 482 M61 498Q134 483 210 498 M394 470Q422 455 449 457 M40 454Q69 445 94 451" /></g>
  <g class="botanical">
    <g class="stems"><path d="${[twig, ...branches, shrub, ...petioles].map(stem).join(' ')}" /></g>
    <g class="needles" stroke-width=".8"><path d="${[pineNeedles(twig, leader), ...branches.map(branch => pineNeedles(branch, branch))].join(' ')}" /></g>
    <g class="leaves" fill="currentColor" fill-opacity=".08">
      ${leaves.map(leaf => `<path d="${leaf.outline}" />`).join('\n      ')}
    </g>
    <g class="midribs" stroke-width=".85"><path d="${leaves.map(leaf => leaf.midrib).join(' ')}" /></g>
    <g class="veins" stroke-width=".65" opacity=".6"><path d="${leaves.map(leaf => leaf.veins).join(' ')}" /></g>
  </g>
</svg>
`
}
