// One rounded, oak-like leaf template on an alternating spray. Branch roots
// come from the main twig; each leaf inherits its branch's terminal tangent.
export const broadleafScene = {
  twig: { base: [392, 513], bend: [294, 345], tip: [236, 170] },
  terminal: { length: 135, width: 43 },
  branches: [
    { at: .28, bend: [285, 401], tip: [233, 379], length: 105, width: 34 },
    { at: .45, bend: [315, 300], tip: [354, 245], length: 125, width: 43 },
    { at: .68, bend: [230, 268], tip: [180, 252], length: 113, width: 37 },
  ],
}

const point = xy => xy.map(value => Number(value.toFixed(3))).join(' ')
const onCurve = ({ base, bend, tip }, t) => base.map((value, axis) =>
  (1 - t) ** 2 * value + 2 * t * (1 - t) * bend[axis] + t ** 2 * tip[axis])
const stem = ({ base, bend, tip }) => `M${point(base)} Q${point(bend)} ${point(tip)}`

// Normalized cubic segments, proceeding around the rounded lobes from the
// petiole. All sizes share this outline; only scale and orientation vary.
const oakOutline = [
  [-.12, -.025, -.32, .01, -.27, .10],
  [-.80, .03, -1, .18, -.55, .24],
  [-1.2, .21, -1.2, .42, -.62, .43],
  [-1.22, .48, -1, .64, -.52, .62],
  [-.95, .73, -.69, .85, -.32, .79],
  [-.50, .92, -.22, 1.03, 0, 1],
  [.22, 1.03, .50, .92, .32, .79],
  [.99, .90, 1.16, .68, .57, .62],
  [1.26, .70, 1.34, .44, .64, .43],
  [1.22, .41, 1.04, .19, .55, .24],
  [.98, .09, .64, .02, .27, .10],
  [.32, .01, .12, -.025, 0, 0],
]

function oakLeaf({ bend, tip, length, width }) {
  const direction = tip.map((value, axis) => value - bend[axis])
  const magnitude = Math.hypot(...direction)
  const [dx, dy] = direction.map(value => value / magnitude)
  const local = (x, y) => point([
    tip[0] - dy * x * width + dx * y * length,
    tip[1] + dx * x * width + dy * y * length,
  ])
  const outline = `M${local(0, 0)} ` + oakOutline.map(segment =>
    `C${local(segment[0], segment[1])} ${local(segment[2], segment[3])} ${local(segment[4], segment[5])}`).join(' ') + ' Z'
  // Every vein starts on the same midrib and ends inside its matching lobe.
  const veins = [[.07, .60, .14], [.24, .85, .33], [.43, .79, .54], [.63, .58, .75]]
    .flatMap(([start, x, y]) => [-1, 1].map(side =>
      `M${local(0, start)} Q${local(side * x * .4, y - .05)} ${local(side * x, y)}`)).join(' ')
  return { outline, midrib: `M${local(0, 0)} L${local(0, 1)}`, veins }
}

export function generateBroadleafSvg() {
  const { twig, terminal } = broadleafScene
  const branches = broadleafScene.branches.map(branch => ({ ...branch, base: onCurve(twig, branch.at) }))
  const leaves = [oakLeaf({ ...twig, ...terminal }), ...branches.map(oakLeaf)]
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 460 510" fill="none" stroke="currentColor" stroke-width="1.15" stroke-linecap="round" stroke-linejoin="round">
  <!-- Generated by generators/broadleaf.mjs; edit the scene, then pnpm artwork:generate. -->
  <g class="contours" opacity=".35" stroke-width=".7"><path d="M25 484c80-45 139-7 202-25s133-16 238-55M4 501c91-43 157-4 230-22s156-25 240-53M76 459c52-23 100 1 156-17s135-5 223-58" /></g>
  <g class="botanical">
    <g class="stems"><path d="${[twig, ...branches].map(stem).join(' ')}" /></g>
    <g class="leaves">
      ${leaves.map(leaf => `<path class="sketch-wash" fill="currentColor" fill-opacity=".08" d="${leaf.outline}" />`).join('\n      ')}
    </g>
    <g class="midribs"><path d="${leaves.map(leaf => leaf.midrib).join(' ')}" /></g>
    <g class="veins" stroke-width=".65" opacity=".6"><path d="${leaves.map(leaf => leaf.veins).join(' ')}" /></g>
  </g>
</svg>
`
}
