// A restrained fir-like spray: three separated needle fans and one hanging
// cone. All attachments are evaluated on the same quadratic twig curves.
export const coniferScene = {
  twig: { base: [392, 513], bend: [300, 345], tip: [238, 90] },
  leader: { from: .61, to: .985, count: 17, length: 31 },
  branches: [
    { at: .40, bend: [230, 307], tip: [127, 252], from: .24, to: .97, count: 14, length: 29 },
    { at: .52, bend: [352, 258], tip: [386, 179], from: .26, to: .97, count: 12, length: 27 },
  ],
  cone: { branch: 0, at: .15, top: [283, 367], length: 72, width: 24, angle: -8 },
}

const point = xy => xy.map(value => Number(value.toFixed(3))).join(' ')
const onCurve = ({ base, bend, tip }, t) => base.map((value, axis) =>
  (1 - t) ** 2 * value + 2 * t * (1 - t) * bend[axis] + t ** 2 * tip[axis])
const tangent = ({ base, bend, tip }, t) => base.map((value, axis) =>
  2 * (1 - t) * (bend[axis] - value) + 2 * t * (tip[axis] - bend[axis]))
const stem = ({ base, bend, tip }) => `M${point(base)} Q${point(bend)} ${point(tip)}`

function needles(curve, { from, to, count, length }) {
  const paths = []
  for (let index = 0; index < count; index++) {
    const progress = index / (count - 1)
    for (const side of [-1, 1]) {
      // Slightly stagger the two rows. Shorter needles at both ends make a
      // tapered fan, with no long crossing strokes at the growing tip.
      const t = from + (to - from) * progress + (side === 1 ? .007 : 0)
      const origin = onCurve(curve, t)
      const direction = tangent(curve, t)
      const magnitude = Math.hypot(...direction)
      const [dx, dy] = direction.map(value => value / magnitude)
      const size = length * (.38 + .62 * Math.sin(Math.PI * progress) ** .7)
      const local = (across, forward) => point([
        origin[0] - dy * across + dx * forward,
        origin[1] + dx * across + dy * forward,
      ])
      paths.push(`M${point(origin)} Q${local(side * size * .52, size * .20)} ${local(side * size * .82, size * .58)}`)
    }
  }
  return paths.join(' ')
}

function hangingCone(twig, { at, top, length, width, angle }) {
  const root = onCurve(twig, at)
  const radians = angle * Math.PI / 180
  const dx = Math.sin(radians)
  const dy = Math.cos(radians)
  const local = (x, y) => point([
    top[0] + dy * x * width + dx * y * length,
    top[1] - dx * x * width + dy * y * length,
  ])
  const stalk = `M${point(root)} Q${point([top[0] + 5, root[1] + 4])} ${local(0, 0)}`
  const outline = `M${local(0, 0)} C${local(-.5, -.02)} ${local(-1, .16)} ${local(-1, .4)} C${local(-1, .67)} ${local(-.5, .94)} ${local(0, 1)} C${local(.5, .94)} ${local(1, .67)} ${local(1, .4)} C${local(1, .16)} ${local(.5, -.02)} ${local(0, 0)} Z`
  const rows = [[.14, .64, 2], [.27, .85, 3], [.40, .87, 3], [.53, .76, 3], [.66, .60, 2], [.79, .35, 1]]
  const scales = rows.flatMap(([y, halfWidth, count]) => Array.from({ length: count }, (_, index) => {
    const left = -halfWidth + 2 * halfWidth * index / count
    const right = -halfWidth + 2 * halfWidth * (index + 1) / count
    return `M${local(left, y)} Q${local((left + right) / 2, y + .16)} ${local(right, y)}`
  })).join(' ')
  return { stalk, outline, scales }
}

export function generateConiferSvg() {
  const { twig, leader } = coniferScene
  const branches = coniferScene.branches.map(branch => ({ ...branch, base: onCurve(twig, branch.at) }))
  const cone = hangingCone(branches[coniferScene.cone.branch], coniferScene.cone)
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 460 510" fill="none" stroke="currentColor" stroke-width="1.15" stroke-linecap="round" stroke-linejoin="round">
  <!-- Generated by generators/conifer.mjs; edit the scene, then pnpm artwork:generate. -->
  <g class="contours" opacity=".35" stroke-width=".7"><path d="M25 484c80-45 139-7 202-25s133-16 238-55M4 501c91-43 157-4 230-22s156-25 240-53M76 459c52-23 100 1 156-17s135-5 223-58" /></g>
  <g class="botanical">
    <g class="stems"><path d="${[twig, ...branches].map(stem).join(' ')} ${cone.stalk}" /></g>
    <g class="needles" stroke-width=".9"><path d="${[needles(twig, leader), ...branches.map(branch => needles(branch, branch))].join(' ')}" /></g>
    <g class="cone">
      <path fill="currentColor" fill-opacity=".06" d="${cone.outline}" />
      <path class="scales" stroke-width=".75" opacity=".8" d="${cone.scales}" />
    </g>
  </g>
</svg>
`
}
