// Grassland and savanna share this scene. Leaves use each curved stalk's
// attachment point and tipward tangent, never an independent row of offsets.
export const grasslandScene = [
  { base: [325, 500], bend: [275, 335], tip: [303, 130], head: { offset: 25, spacing: 16, sides: [-1, 1], width: 26, length: 38 } },
  { base: [316, 466], bend: [204, 349], tip: [167, 228], head: { offset: 22, spacing: 14, sides: [-1], width: 22, length: 30 } },
  { base: [335, 500], bend: [394, 342], tip: [393, 230], head: { offset: 22, spacing: 14, sides: [-1, 1], width: 20, length: 31 } },
  { base: [308, 450], bend: [256, 300], tip: [225, 200] },
  { base: [338, 480], bend: [352, 353], tip: [340, 290] },
  { base: [283, 460], bend: [187, 410], tip: [107, 390] },
]

const number = value => Number(value.toFixed(3))
const point = xy => xy.map(number).join(' ')

function onStalk({ base, bend, tip }, t) {
  return base.map((value, axis) => (1 - t) ** 2 * value + 2 * (1 - t) * t * bend[axis] + t ** 2 * tip[axis])
}

// Measure down from the tip so spacing stays even on differently curved stalks.
function attachmentParameters(stalk) {
  const parameters = []
  let distance = 0
  let previous = stalk.tip
  let next = stalk.head.offset
  for (let step = 1; step <= 400 && parameters.length < 7; step++) {
    const t = 1 - step / 400
    const current = onStalk(stalk, t)
    const segment = Math.hypot(current[0] - previous[0], current[1] - previous[1])
    if (distance + segment >= next) {
      parameters.push(t + (1 - (next - distance) / segment) / 400)
      next += stalk.head.spacing
    }
    distance += segment
    previous = current
  }
  return parameters
}

function leaf(stalk, t, side) {
  const origin = onStalk(stalk, t)
  const tangent = stalk.base.map((base, axis) => 2 * (1 - t) * (stalk.bend[axis] - base) + 2 * t * (stalk.tip[axis] - stalk.bend[axis]))
  const magnitude = Math.hypot(...tangent)
  const [dx, dy] = tangent.map(value => value / magnitude)
  const { width, length } = stalk.head
  // Local x is perpendicular to the stalk; local y points toward its tip.
  const local = (x, y) => point([origin[0] - dy * x + dx * y, origin[1] + dx * x + dy * y])
  const base = point(origin)
  return `<path d="M${base} Q${local(side * width * 1.3, length * .36)} ${local(side * width, length)} Q${local(0, length * .75)} ${base}" />`
}

export function generateGrasslandSvg() {
  const stems = grasslandScene.map(stalk => `M${point(stalk.base)} Q${point(stalk.bend)} ${point(stalk.tip)}`).join(' ')
  const leaves = grasslandScene.filter(stalk => stalk.head).flatMap(stalk =>
    attachmentParameters(stalk).flatMap(t => stalk.head.sides.map(side => leaf(stalk, t, side))))
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 460 510" fill="none" stroke="currentColor" stroke-width="1.15" stroke-linecap="round" stroke-linejoin="round">
  <!-- Generated by generators/grassland.mjs; edit the scene, then pnpm artwork:generate. -->
  <g class="contours" opacity=".35" stroke-width=".7"><path d="M25 484c80-45 139-7 202-25s133-16 238-55M4 501c91-43 157-4 230-22s156-25 240-53M76 459c52-23 100 1 156-17s135-5 223-58" /></g>
  <g class="botanical">
    <g class="stems"><path d="${stems}" /></g>
    <g class="leaves">
      ${leaves.join('\n      ')}
    </g>
  </g>
</svg>
`
}
