import { frame, onCurve, point, simpleLeaf, stem, tangent } from './botanical-geometry.mjs'

// An evergreen spray and a low fern: moist-forest motifs shared by the two
// ecoregions, rather than a species portrait of either city.
export const tropicalScene = {
  twig: { base: [400, 513], bend: [300, 348], tip: [256, 192] },
  terminal: { length: 142, width: 39 },
  branches: [
    { at: .27, bend: [287, 379], tip: [242, 355], length: 112, width: 35 },
    { at: .50, bend: [325, 302], tip: [354, 270], length: 121, width: 37 },
    { at: .72, bend: [237, 281], tip: [204, 262], length: 112, width: 33 },
  ],
  fern: { base: [351, 513], bend: [253, 420], tip: [102, 395], count: 12, length: 43 },
}

function fernFrond(curve) {
  const outlines = []
  const ribs = []
  for (let index = 0; index < curve.count; index++) {
    const progress = index / (curve.count - 1)
    for (const side of [-1, 1]) {
      const t = .23 + .73 * progress + (side === 1 ? .012 : 0)
      const origin = onCurve(curve, t)
      const position = frame(origin, tangent(curve, t))
      const size = curve.length * (.2 + .8 * Math.sin(Math.PI * (.15 + .85 * progress)))
      const local = (x, y) => point(position(side * x * size, y * size))
      outlines.push(`M${point(origin)} C${local(.24, -.03)} ${local(.8, .19)} ${local(.91, .61)} C${local(.59, .48)} ${local(.12, .26)} ${point(origin)} Z`)
      ribs.push(`M${point(origin)} Q${local(.44, .22)} ${local(.91, .61)}`)
    }
  }
  return { outlines: outlines.join(' '), ribs: ribs.join(' ') }
}

export function generateTropicalSvg() {
  const { twig, terminal, fern } = tropicalScene
  const branches = tropicalScene.branches.map(branch => ({ ...branch, base: onCurve(twig, branch.at) }))
  const leaves = [{ ...twig, ...terminal }, ...branches].map(branch => simpleLeaf(branch, branch.length, branch.width, true))
  const frond = fernFrond(fern)
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 460 510" fill="none" stroke="currentColor" stroke-width="1.15" stroke-linecap="round" stroke-linejoin="round">
  <!-- Generated by generators/tropical.mjs; edit the scene, then pnpm artwork:generate. -->
  <g class="contours" opacity=".35" stroke-width=".7"><path d="M24 474Q104 440 176 465T328 457 M66 493Q155 471 229 487T434 463 M18 453Q59 434 94 445" /></g>
  <g class="botanical">
    <g class="stems"><path d="${[twig, ...branches, fern].map(stem).join(' ')}" /></g>
    <g class="leaves" fill="currentColor" fill-opacity=".08">
      ${leaves.map(leaf => `<path d="${leaf.outline}" />`).join('\n      ')}
    </g>
    <g class="midribs"><path d="${leaves.map(leaf => leaf.midrib).join(' ')}" /></g>
    <g class="veins" stroke-width=".65" opacity=".6"><path d="${leaves.map(leaf => leaf.veins).join(' ')}" /></g>
    <g class="fern" stroke-width=".85"><path d="${frond.outlines}" /><path opacity=".55" stroke-width=".65" d="${frond.ribs}" /></g>
  </g>
</svg>
`
}
