// Olive-inspired spray: shared curve coordinates keep every branch and leaf
// connected. Leaf angles are measured from the stalk's local tipward tangent.
export const woodlandScene = {
  twig: { base: [412, 517], bend: [286, 361], tip: [235, 127] },
  leaves: [
    { at: .93, angle: -5, length: 116, width: 29 },
    { at: .80, angle: 65, length: 120, width: 27 },
    { at: .66, angle: -32, length: 116, width: 29 },
    { at: .49, angle: 70, length: 123, width: 28 },
    { at: .28, angle: 76, length: 119, width: 28 },
  ],
  branches: [
    { at: .41, bend: [377, 303], tip: [410, 233], length: 75, width: 20 },
    { at: .66, bend: [187, 249], tip: [124, 186], length: 55, width: 20 },
    { at: .28, bend: [248, 386], tip: [185, 320], length: 90, width: 25 },
  ],
  olives: [
    { at: .80, offset: [18, 18], angle: 12, length: 27, width: 8 },
    { at: .80, offset: [40, 10], angle: 24, length: 25, width: 8 },
    { at: .49, offset: [-21, 17], angle: -12, length: 28, width: 8.5 },
    { at: .49, offset: [-41, 8], angle: -28, length: 25, width: 8 },
  ],
}

const point = xy => xy.map(value => Number(value.toFixed(3))).join(' ')
const onCurve = ({ base, bend, tip }, t) => base.map((value, axis) =>
  (1 - t) ** 2 * value + 2 * t * (1 - t) * bend[axis] + t ** 2 * tip[axis])
const tangent = ({ base, bend, tip }, t) => base.map((value, axis) =>
  2 * (1 - t) * (bend[axis] - value) + 2 * t * (tip[axis] - bend[axis]))
const stem = ({ base, bend, tip }) => `M${point(base)} Q${point(bend)} ${point(tip)}`

function oliveLeaf(stalk, { at = 1, angle = 0, length, width }) {
  const base = onCurve(stalk, at)
  const direction = tangent(stalk, at)
  const magnitude = Math.hypot(...direction)
  const [tx, ty] = direction.map(value => value / magnitude)
  const radians = angle * Math.PI / 180
  const dx = tx * Math.cos(radians) - ty * Math.sin(radians)
  const dy = ty * Math.cos(radians) + tx * Math.sin(radians)
  const local = (x, y) => point([base[0] - dy * x * width + dx * y * length, base[1] + dx * x * width + dy * y * length])
  // The original narrow, pointed silhouette, with a slight asymmetric bend.
  const outline = `M${local(0, 0)} Q${local(-1.35, .43)} ${local(.10, 1)} Q${local(1.15, .48)} ${local(0, 0)} Z`
  const vein = `M${local(0, 0)} Q${local(.08, .5)} ${local(.10, 1)}`
  return { outline, vein }
}

function oliveFruit(stalk, { at, offset, angle, length, width }) {
  const root = onCurve(stalk, at)
  const top = root.map((value, axis) => value + offset[axis])
  const radians = angle * Math.PI / 180
  const dx = Math.sin(radians)
  const dy = Math.cos(radians)
  const local = (x, y) => point([top[0] + dy * x * width + dx * y * length, top[1] - dx * x * width + dy * y * length])
  // Each fruit starts exactly at its pedicel tip; the twig attachment uses
  // the same curve as the leaves. Rounded ends distinguish olives from leaves.
  const pedicel = `M${point(root)} Q${point([top[0], root[1] + offset[1] * .3])} ${local(0, 0)}`
  const outline = `M${local(0, 0)} C${local(.55, 0)} ${local(1, .22)} ${local(1, .5)} C${local(1, .78)} ${local(.55, 1)} ${local(0, 1)} C${local(-.55, 1)} ${local(-1, .78)} ${local(-1, .5)} C${local(-1, .22)} ${local(-.55, 0)} ${local(0, 0)} Z`
  const highlight = `M${local(-.35, .20)} Q${local(-.65, .38)} ${local(-.45, .57)}`
  return { pedicel, outline, highlight }
}

export function generateWoodlandSvg() {
  const { twig } = woodlandScene
  const branches = woodlandScene.branches.map(branch => ({ ...branch, base: onCurve(twig, branch.at) }))
  const leaves = [
    ...woodlandScene.leaves.map(leaf => oliveLeaf(twig, leaf)),
    ...branches.map(branch => oliveLeaf(branch, { length: branch.length, width: branch.width })),
  ]
  const olives = woodlandScene.olives.map(fruit => oliveFruit(twig, fruit))
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 460 510" fill="none" stroke="currentColor" stroke-width="1.15" stroke-linecap="round" stroke-linejoin="round">
  <!-- Generated by generators/woodland.mjs; edit the scene, then pnpm artwork:generate. -->
  <g class="contours" opacity=".35" stroke-width=".7"><path d="M25 484c80-45 139-7 202-25s133-16 238-55M4 501c91-43 157-4 230-22s156-25 240-53M76 459c52-23 100 1 156-17s135-5 223-58" /></g>
  <g class="botanical">
    <g class="stems"><path d="${[twig, ...branches].map(stem).join(' ')}" /></g>
    <g class="leaves">
      ${leaves.map(leaf => `<path class="sketch-wash" fill="currentColor" fill-opacity=".08" d="${leaf.outline}" />`).join('\n      ')}
    </g>
    <g class="midribs"><path d="${leaves.map(leaf => leaf.vein).join(' ')}" /></g>
    <g class="fruit-stems"><path d="${olives.map(fruit => fruit.pedicel).join(' ')}" /></g>
    <g class="olives" fill="currentColor" fill-opacity=".16">
      ${olives.map(fruit => `<path d="${fruit.outline}" />`).join('\n      ')}
    </g>
    <g class="fruit-detail" stroke-width=".65" opacity=".6"><path d="${olives.map(fruit => fruit.highlight).join(' ')}" /></g>
  </g>
</svg>
`
}
