#!/usr/bin/env -S uv run
# /// script
# requires-python = ">=3.13"
# dependencies = ["duckdb", "requests"]
# ///
"""Fit the genus-level crown-width model tree_predictions.preql applies.

    cd data/raw && uv run crown_allometry_fit.py --write            # refit from Tallo
    cd data/raw && uv run crown_allometry_fit.py --check            # exit 1 if stale
    cd data/raw && uv run crown_allometry_fit.py --write --coverage # + rollup coverage

Source
------
Tallo (Jucker et al. 2022, Global Change Biology, doi:10.1111/gcb.16302): 498,838
georeferenced trees with stem diameter, height and/or crown radius, 312,829 of
them with a crown radius, across 1,453 genera. Archived on Zenodo under CC-BY
4.0 (doi:10.5281/zenodo.6637599); the same files are mirrored at
https://github.com/selva-lab-repo/TALLO, which is where this script downloads
from when `--tallo` is not given, because Zenodo rate-limits scripted downloads.

It is the only open dataset that supports a *genus*-level fit. The published
urban models are species-level and narrow -- McPherson et al. (2016, USFS
PSW-GTR-253) cover ~170 species by US climate zone, Pretzsch et al. (2015,
Urban For. Urban Green. 14:466) cover 22 species, Coombes et al. (2019, Urban
For. Urban Green. 44:126421) four -- and the FIA models (Bechtold 2003, 2004)
are species-level and stand-grown. The rollup carries ~900 genera.

Model
-----
    ln(crown_radius_m) = ln_a + b * ln(stem_diameter_cm)

fitted by ordinary least squares in log-log space per genus, with the
back-transform bias corrected (Baskerville 1972): the `scale` column is
`exp(ln_a + sigma^2 / 2)`, so the prediction the model applies is simply

    crown_width_m = 2 * scale * dbh_cm ** b

which needs no `exp` or `ln` -- pytrilogy has neither natively -- only
`power`. A power law is the standard form for this relationship (crown
radius, not area: the exponent is 0.5-0.85 for these forest-dominated data,
and would be nearer 1.0 for open-grown urban trees, see below).

Fallback resolution happens here, at fit time, so the model does one join:
every genus Tallo knows gets a row whose coefficients are its own fit when
that fit passes the gate below, else its family's fit, else its division's
(angiosperm / gymnosperm). `fit_level` and `fit_taxon` record which. A genus
Tallo has never heard of (Syringa, Washingtonia, Koelreuteria, ...) falls
through to the division constants the `--write` step renders into the
model's generated block, chosen by the enrichment table's `tree_form`.

The gate: n >= 30, r2 >= 0.2, 0.3 <= b <= 1.3, and a largest fitted stem of
at least 20 cm. Without it Malus (n = 33, b = -0.11, r2 = 0.00) and Ostrya
(n = 1,482, b = 0.17, r2 = 0.03) would ship fits that make crowns *shrink*
with diameter, and a genus measured only as saplings would clamp every street
tree of that genus to a sapling's crown.

Stem diameter is clamped to the fitted range before prediction (`dbh_max_cm`),
so a data-entry DBH of 400 inches predicts the crown of the largest tree the
genus was fitted on rather than a power-law extrapolation.

What this model is not
----------------------
Tallo is forest plots, not street trees; open-grown urban crowns are wider
per unit of stem. Coombes et al. (2019) measured 400 free-standing urban
broadleaves in two UK cities and found crown diameter / DBH settling at about
25:1 for DBH >= 0.3 m (pooled fit: CD = 0.8304 + 27.82 D - 10.68 D^2, metres).
Against that, the Tallo genus fits run roughly 15-30% low for a 30-60 cm
broadleaf, and the gap widens with size because their exponents are below 1.
`--write` prints the comparison for the commonest genera. It is deliberately
not applied: it is four species in one climate, and the point of this table
is one sourced model per genus with its provenance attached. Calibrating the
urban offset is the curation step this dataset exists to feed.

Stand density is *not* a term. Tallo records no competition measure, and the
one large study that tried one -- Bechtold (2003), 87 species, FHM plots --
found the stand basal-area coefficient "a mixture of positive and negative"
signs with partial r-squares under 0.02 and dropped it. The prediction
parquet still carries a per-tree density covariate (trees per hectare in a
50 m cell, from the rollup's own coordinates) so the curation stage can look
at crown width against it; it does not enter the prediction.
"""

from __future__ import annotations

import argparse
import csv
import io
import math
import sys
import zipfile
from pathlib import Path

import duckdb

HERE = Path(__file__).resolve().parent
COEFFICIENTS_CSV = HERE / "crown_width_coefficients.csv"
MODEL = HERE / "tree_predictions.preql"
BEGIN = "# BEGIN crown_fallbacks -- generated by crown_allometry_fit.py from crown_width_coefficients.csv; do not edit\n"
END = "# END crown_fallbacks\n"

TALLO_ZIP_URL = "https://raw.githubusercontent.com/selva-lab-repo/TALLO/main/DB/Tallo.csv.zip"
TALLO_VERSION = "Tallo 1.0.0 (Jucker et al. 2022)"
TALLO_CACHE = HERE / ".cache" / "Tallo.csv"

ROLLUP_URL = "https://storage.googleapis.com/trilogy_public_models/duckdb/trees/full_tree_info_v2.parquet"

MIN_N = 30
MIN_R2 = 0.2
B_RANGE = (0.3, 1.3)
MIN_DBH_CM = 1.0
MIN_FITTED_DBH_MAX_CM = 20.0  # a fit made on saplings alone would clamp every street tree to a sapling's crown

CSV_COLUMNS = [
    "level",        # genus | family | division | global
    "taxon",        # the genus / family / division name, or 'all'
    "family",       # of a genus row; blank otherwise
    "division",     # Angiosperm | Gymnosperm, where Tallo knows it
    "fit_level",    # which fit a genus row carries: genus | family | division
    "fit_taxon",    # the taxon that fit came from
    "n",
    "ln_a",
    "b",
    "sigma",
    "r2",
    "dbh_min_cm",
    "dbh_max_cm",
    "scale",        # exp(ln_a + sigma^2/2): crown_radius_m = scale * dbh_cm ** b
]

FIT_SQL = """
SELECT
    {group} AS taxon,
    count(*) AS n,
    regr_intercept(y, x) AS ln_a,
    regr_slope(y, x) AS b,
    sqrt(regr_syy(y, x) * (1 - regr_r2(y, x)) / (count(*) - 2)) AS sigma,
    regr_r2(y, x) AS r2,
    min(exp(x)) AS dbh_min_cm,
    max(exp(x)) AS dbh_max_cm
FROM usable
WHERE {group} IS NOT NULL
GROUP BY 1
HAVING count(*) >= {min_n}
"""


def tallo_path(explicit: str | None) -> Path:
    if explicit:
        path = Path(explicit)
        if not path.is_file():
            sys.exit(f"--tallo {path} does not exist")
        return path
    if TALLO_CACHE.is_file():
        return TALLO_CACHE
    import requests  # noqa: PLC0415  (only the download path needs it)

    print(f"downloading {TALLO_ZIP_URL} to {TALLO_CACHE}", file=sys.stderr)
    response = requests.get(TALLO_ZIP_URL, timeout=300)
    response.raise_for_status()
    with zipfile.ZipFile(io.BytesIO(response.content)) as archive:
        member = next(n for n in archive.namelist() if n.endswith("Tallo.csv") and "__MACOSX" not in n)
        TALLO_CACHE.parent.mkdir(parents=True, exist_ok=True)
        TALLO_CACHE.write_bytes(archive.read(member))
    return TALLO_CACHE


def load(conn: duckdb.DuckDBPyConnection, path: Path) -> None:
    conn.execute(
        "CREATE TABLE tallo AS SELECT * FROM read_csv(?, header = true, nullstr = 'NA')",
        [str(path)],
    )
    # Log-log rows the fit uses: a crown radius, a stem diameter, not flagged.
    conn.execute(
        f"""
        CREATE TABLE usable AS
        SELECT genus, family, division,
               ln(stem_diameter_cm) AS x, ln(crown_radius_m) AS y
        FROM tallo
        WHERE crown_radius_m > 0
          AND stem_diameter_cm >= {MIN_DBH_CM}
          AND crown_radius_outlier = 'N'
        """
    )


def passes_gate(row: dict) -> bool:
    return (
        row["n"] >= MIN_N
        and row["r2"] is not None
        and row["r2"] >= MIN_R2
        and B_RANGE[0] <= row["b"] <= B_RANGE[1]
        and row["dbh_max_cm"] >= MIN_FITTED_DBH_MAX_CM
    )


def fits(conn: duckdb.DuckDBPyConnection, group: str) -> dict[str, dict]:
    columns = ["taxon", "n", "ln_a", "b", "sigma", "r2", "dbh_min_cm", "dbh_max_cm"]
    rows = conn.execute(FIT_SQL.format(group=group, min_n=MIN_N)).fetchall()
    return {r[0]: dict(zip(columns, r)) for r in rows}


def with_scale(row: dict) -> dict:
    out = dict(row)
    out["scale"] = math.exp(row["ln_a"] + row["sigma"] ** 2 / 2)
    return out


def build_rows(conn: duckdb.DuckDBPyConnection) -> list[dict]:
    genus_fits = fits(conn, "genus")
    family_fits = fits(conn, "family")
    division_fits = fits(conn, "division")
    global_fit = fits(conn, "'all'")["all"]

    # Every genus Tallo knows, with its family and division -- including the
    # ones with no crown measurement at all, which still get a fallback row so
    # a tree of that genus resolves to the right division rather than to the
    # enrichment table's guess at its form.
    taxonomy = conn.execute(
        """
        SELECT genus, any_value(family), any_value(division)
        FROM tallo WHERE genus IS NOT NULL GROUP BY 1 ORDER BY 1
        """
    ).fetchall()

    rows: list[dict] = []
    for genus, family, division in taxonomy:
        candidates = [
            ("genus", genus, genus_fits.get(genus)),
            ("family", family, family_fits.get(family) if family else None),
            ("division", division, division_fits.get(division) if division else None),
            ("global", "all", global_fit),
        ]
        for fit_level, fit_taxon, fit in candidates:
            if fit is not None and passes_gate(fit):
                break
        else:  # pragma: no cover - the global fit always passes
            raise RuntimeError("no fit passed the gate, not even the global one")
        rows.append(
            {
                "level": "genus",
                "taxon": genus,
                "family": family or "",
                "division": division or "",
                "fit_level": fit_level,
                "fit_taxon": fit_taxon,
                **{k: v for k, v in with_scale(fit).items() if k != "taxon"},
            }
        )
    for family, fit in sorted(family_fits.items()):
        if passes_gate(fit):
            rows.append(
                {"level": "family", "taxon": family, "family": family, "division": "",
                 "fit_level": "family", "fit_taxon": family,
                 **{k: v for k, v in with_scale(fit).items() if k != "taxon"}}
            )
    for division, fit in sorted(division_fits.items()):
        assert passes_gate(fit), f"the {division} fit failed the gate"
        rows.append(
            {"level": "division", "taxon": division, "family": "", "division": division,
             "fit_level": "division", "fit_taxon": division,
             **{k: v for k, v in with_scale(fit).items() if k != "taxon"}}
        )
    rows.append(
        {"level": "global", "taxon": "all", "family": "", "division": "",
         "fit_level": "global", "fit_taxon": "all",
         **{k: v for k, v in with_scale(global_fit).items() if k != "taxon"}}
    )
    return rows


def format_row(row: dict) -> dict[str, str]:
    out = {}
    for column in CSV_COLUMNS:
        value = row[column]
        if isinstance(value, float):
            out[column] = f"{value:.6g}"
        else:
            out[column] = str(value)
    return out


def write_csv(rows: list[dict]) -> None:
    with COEFFICIENTS_CSV.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=CSV_COLUMNS, lineterminator="\n")
        writer.writeheader()
        for row in rows:
            writer.writerow(format_row(row))


def read_csv_rows() -> list[dict[str, str]]:
    with COEFFICIENTS_CSV.open(encoding="utf-8", newline="") as handle:
        return list(csv.DictReader(handle))


def render_block(rows: list[dict[str, str]]) -> str:
    """The division and global constants, as `const` declarations.

    These are the fallbacks for a genus the coefficient table does not carry;
    they are rendered into the model rather than read from the CSV because a
    derived value (the division chosen from `tree_form`) cannot be a join key
    without a merge, and three constants are simpler than one.
    """
    by_key = {(r["level"], r["taxon"]): r for r in rows}
    lines = [BEGIN, f"# {TALLO_VERSION}: crown_radius_m = scale * dbh_cm ** b, dbh clamped to [1, dbh_max_cm]\n"]
    for label, key in (
        ("angiosperm", ("division", "Angiosperm")),
        ("gymnosperm", ("division", "Gymnosperm")),
        ("global", ("global", "all")),
    ):
        row = by_key[key]
        lines.append(f"const {label}_crown_scale <- {float(row['scale']):.6g};\n")
        lines.append(f"const {label}_crown_b <- {float(row['b']):.6g};\n")
        lines.append(f"const {label}_crown_n <- {int(row['n'])};\n")
        lines.append(f"const {label}_crown_dbh_max_cm <- {float(row['dbh_max_cm']):.6g};\n")
    lines.append(END)
    return "".join(lines)


def splice_block(text: str, block: str) -> str:
    start = text.index(BEGIN)
    end = text.index(END) + len(END)
    return text[:start] + block + text[end:]


def current_block(text: str) -> str:
    start = text.index(BEGIN)
    end = text.index(END) + len(END)
    return text[start:end]


def report(conn: duckdb.DuckDBPyConnection, rows: list[dict], coverage: bool) -> None:
    genus_rows = [r for r in rows if r["level"] == "genus"]
    by_level = {}
    for r in genus_rows:
        by_level[r["fit_level"]] = by_level.get(r["fit_level"], 0) + 1
    print(f"{len(genus_rows)} genera: {by_level}", file=sys.stderr)

    # Against Coombes et al. (2019): open-grown urban broadleaves settle at a
    # crown diameter of about 25 x DBH from 0.3 m up.
    print("crown diameter at 30 / 60 cm DBH, metres (Coombes urban ref: 8.2 / 13.7):", file=sys.stderr)
    lookup = {r["taxon"]: r for r in genus_rows}
    for genus in ("Acer", "Quercus", "Fraxinus", "Tilia", "Ulmus", "Platanus", "Prunus",
                  "Gleditsia", "Pinus", "Picea", "Malus", "Betula"):
        r = lookup.get(genus)
        if r is None:
            continue
        cd = [2 * r["scale"] * d ** r["b"] for d in (30, 60)]
        print(f"  {genus:<10} {cd[0]:5.1f} {cd[1]:5.1f}   ({r['fit_level']} fit, n={r['n']}, b={r['b']:.2f}, r2={r['r2']:.2f})", file=sys.stderr)

    if not coverage:
        return
    conn.execute("INSTALL httpfs; LOAD httpfs")
    conn.execute("CREATE TABLE genus_rows AS SELECT * FROM read_csv(?)", [str(COEFFICIENTS_CSV)])
    share = conn.execute(
        f"""
        WITH ours AS (
            SELECT split_part(species, ' ', 1) AS genus, count(*) AS n
            FROM read_parquet('{ROLLUP_URL}')
            WHERE species NOT IN ('Unknown', 'Palm', 'Shrub', 'Cactus', 'Dead')
            GROUP BY 1
        )
        SELECT coalesce(g.fit_level, 'not in Tallo') AS level, sum(o.n) AS trees
        FROM ours o LEFT JOIN genus_rows g ON g.level = 'genus' AND g.taxon = o.genus
        GROUP BY 1 ORDER BY 2 DESC
        """
    ).fetchall()
    total = sum(n for _, n in share)
    print("identified trees in the published rollup, by the fit they would get:", file=sys.stderr)
    for level, n in share:
        print(f"  {level:<14} {n:>10,}  {100 * n / total:5.1f}%", file=sys.stderr)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--write", action="store_true", help="refit from Tallo and rewrite the CSV and the model's fallback block")
    parser.add_argument("--check", action="store_true", help="exit 1 if the model's fallback block disagrees with the CSV")
    parser.add_argument("--tallo", help="path to Tallo.csv (downloaded and cached when omitted)")
    parser.add_argument("--coverage", action="store_true", help="also report coverage against the published rollup (network)")
    args = parser.parse_args()

    if args.check:
        rows = read_csv_rows()
        text = MODEL.read_text(encoding="utf-8")
        if current_block(text) != render_block(rows):
            print(f"{MODEL.name}'s crown_fallbacks block is stale; run crown_allometry_fit.py --write", file=sys.stderr)
            return 1
        print("crown_fallbacks block is current")
        return 0

    if not args.write:
        parser.error("one of --write or --check is required")

    conn = duckdb.connect()
    load(conn, tallo_path(args.tallo))
    rows = build_rows(conn)
    write_csv(rows)
    text = MODEL.read_text(encoding="utf-8")
    MODEL.write_text(splice_block(text, render_block(read_csv_rows())), encoding="utf-8")
    print(f"wrote {len(rows)} rows to {COEFFICIENTS_CSV.name} and the fallback block in {MODEL.name}", file=sys.stderr)
    report(conn, rows, args.coverage)
    return 0


if __name__ == "__main__":
    sys.exit(main())
