#!/usr/bin/env -S uv run
# /// script
# requires-python = ">=3.13"
# dependencies = ["pyarrow", "pytrilogy"]
# ///
"""Generate the per-city dedup grid table inside raw/tree_dedup.preql.

    cd data/raw && uv run dedup_cells.py --write    # regenerate the block
    cd data/raw && uv run dedup_cells.py --check    # exit 1 if it is stale

The cell size in metres, and why it is what it is for each city, live in
DEDUP_CELL_METRES in _ingest_shared.py.  This script converts metres to
degrees at each city's latitude (from the centre of its CITY_BOUNDS box) and
writes them as an inline `VALUES` table between the BEGIN/END markers in
tree_dedup.preql, so the constant a model consumes can never drift from the
calibration written next to it.

**Why an inline table and not a python datasource.**  The first cut read this
script as `file \\`./dedup_cells.py\\``.  That builds fine in a refresh, but the
same model text is also what the browser's dashboard queries are planned
against, on a resolver service that has the .preql sources and none of the
scripts -- and pytrilogy silently drops a file datasource whose path does not
exist.  The cell-size concepts then had no source at all, and the planner
raised `No datasource exists for root concept local.cell_lon_deg` while
exploring the merge as a way to answer for `diameter_at_breast_height`,
instead of reading the column from the published parquet.  A `query`
datasource is bound wherever the text is parsed.  `test_dedup_cells.py` runs
the `--check`.
"""

import sys
from pathlib import Path

import pyarrow as pa

sys.path.insert(0, str(Path(__file__).parent))
from _ingest_shared import (  # noqa: E402
    DEDUP_CELL_METRES,
    dedup_cell_degrees,
)

MODEL = Path(__file__).parent / "tree_dedup.preql"
BEGIN = "# BEGIN dedup_cells -- generated by dedup_cells.py from DEDUP_CELL_METRES; do not edit\n"
END = "# END dedup_cells\n"


def rows() -> list[tuple[str, float, float]]:
    return [(c, *dedup_cell_degrees(c)) for c in sorted(DEDUP_CELL_METRES)]


def build_table(city: str | None = None) -> pa.Table:
    """The table as Arrow, for tests and for anything that wants it in Python."""
    picked = [r for r in rows() if city is None or r[0] == city]
    return pa.table(
        {
            "city": pa.array([r[0] for r in picked], type=pa.string()),
            "cell_lat_deg": pa.array([r[1] for r in picked], type=pa.float64()),
            "cell_lon_deg": pa.array([r[2] for r in picked], type=pa.float64()),
        }
    )


def render_block() -> str:
    values = ",\n".join(
        f"    ('{code}', {lat:.8f}, {lon:.8f})" for code, lat, lon in rows()
    )
    return (
        BEGIN
        + "root datasource dedup_cells (\n"
        "    city: city,\n"
        "    cell_lat_deg: cell_lat_deg,\n"
        "    cell_lon_deg: cell_lon_deg,\n"
        ")\n"
        "grain (city)\n"
        "query '''\n"
        "SELECT * FROM (VALUES\n"
        f"{values}\n"
        ") AS t(city, cell_lat_deg, cell_lon_deg)\n"
        "''';\n"
        + END
    )


def current_block(text: str) -> str:
    start = text.index(BEGIN)
    end = text.index(END, start) + len(END)
    return text[start:end]


def main(argv: list[str]) -> int:
    text = MODEL.read_text(encoding="utf-8")
    wanted = render_block()
    if "--write" in argv:
        MODEL.write_text(text.replace(current_block(text), wanted), encoding="utf-8")
        print(f"wrote {len(DEDUP_CELL_METRES)} cities into {MODEL.name}")
        return 0
    if current_block(text) != wanted:
        print(
            f"{MODEL.name} is stale against DEDUP_CELL_METRES; run "
            "`uv run dedup_cells.py --write`",
            file=sys.stderr,
        )
        return 1
    print("up to date")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
